version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app
    restart: always
    command: "flask run --host=0.0.0.0 --port=8000"
    ports:
      - "23006:8000"
    env_file:
      - '.env'
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: